# -*- coding: utf-8 -*-
"""midtermreportregressionmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8cMOvY9wCNVwMyLqqRqhZd4xsMPHBix
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix

def prepare_diabetes_data(filepath):
    df = pd.read_csv(filepath)

    # Standardize missing markers
    df = df.replace("?", np.nan)

    # Drop obvious identifier columns / very high-cardinality IDs
    drop_cols = [
        "encounter_id",
        "patient_nbr",
    ]
    existing_drop_cols = [c for c in drop_cols if c in df.columns]
    df = df.drop(columns=existing_drop_cols)

    # Optional: remove weight / payer_code / medical_specialty if too sparse
    sparse_optional = ["weight", "payer_code", "medical_specialty"]
    sparse_existing = [c for c in sparse_optional if c in df.columns]
    df = df.drop(columns=sparse_existing)

    # Create binary target: readmitted within 30 days vs not
    # Common values are '<30', '>30', 'NO'
    if "readmitted" not in df.columns:
        raise ValueError("Expected column 'readmitted' not found in diabetes dataset.")

    df["target"] = (df["readmitted"] == "<30").astype(int)
    df = df.drop(columns=["readmitted"])

    # Convert some numeric-looking columns if present
    numeric_candidates = [
        "time_in_hospital", "num_lab_procedures", "num_procedures",
        "num_medications", "number_outpatient", "number_emergency",
        "number_inpatient", "number_diagnoses"
    ]
    for col in numeric_candidates:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    x = df.drop(columns=["target"])
    y = df["target"]

    return x, y

def prepare_german_credit_data(filepath):
    import pandas as pd

    col_names = [
        "status", "duration", "credit_history", "purpose", "credit_amount",
        "savings", "employment", "installment_rate", "personal_status_sex",
        "other_debtors", "residence_since", "property", "age",
        "other_installment_plans", "housing", "existing_credits",
        "job", "num_dependents", "telephone", "foreign_worker", "target"
    ]

    df = pd.read_csv(filepath, sep=" ", header=None, names=col_names)

    # Convert target: 1 = good, 2 = bad → make 1 = bad
    df["target"] = (df["target"] == 2).astype(int)

    # Extract gender for fairness analysis
    def extract_gender(val):
        if val in ["A91", "A93", "A94"]:
            return "male"
        elif val in ["A92", "A95"]:
            return "female"
        else:
            return "unknown"

    df["gender"] = df["personal_status_sex"].apply(extract_gender)

    x = df.drop(columns=["target"])
    y = df["target"]

    return x, y



def build_preprocessor(X):
    categorical_cols = X.select_dtypes(include=["object", "category"]).columns.tolist()
    numerical_cols = X.select_dtypes(include=[np.number, "bool"]).columns.tolist()

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, numerical_cols),
            ("cat", categorical_transformer, categorical_cols),
        ]
    )

    return preprocessor, numerical_cols, categorical_cols


def build_logistic_model(preprocessor):
    model = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("classifier", LogisticRegression(
            max_iter=2000,
            solver="liblinear",   # stable for many binary tabular problems
            class_weight="balanced"
        ))
    ])
    return model


def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)

    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        y_prob = None

    results = {
        "accuracy": accuracy_score(y_test, y_pred),
        "f1": f1_score(y_test, y_pred),
    }

    if y_prob is not None and len(np.unique(y_test)) > 1:
        results["auc"] = roc_auc_score(y_test, y_prob)
    else:
        results["auc"] = np.nan

    return results, y_pred, y_prob


def fairness_by_group(model, X_test, y_test, group_col):
    if group_col not in X_test.columns:
        raise ValueError(f"Column '{group_col}' not found in X_test.")

    temp = X_test.copy()
    temp["y_true"] = y_test.values
    temp["y_pred"] = model.predict(X_test)

    rows = []

    for group_value in temp[group_col].dropna().unique():
        g = temp[temp[group_col] == group_value]

        y_true_g = g["y_true"]
        y_pred_g = g["y_pred"]

        # confusion matrix in fixed order [0,1]
        tn, fp, fn, tp = confusion_matrix(
            y_true_g, y_pred_g, labels=[0, 1]
        ).ravel()

        positive_rate = (y_pred_g == 1).mean()
        fpr = fp / (fp + tn) if (fp + tn) > 0 else np.nan
        fnr = fn / (fn + tp) if (fn + tp) > 0 else np.nan
        precision = tp / (tp + fp) if (tp + fp) > 0 else np.nan

        rows.append({
            "group_column": group_col,
            "group_value": group_value,
            "n": len(g),
            "positive_rate": positive_rate,
            "FPR": fpr,
            "FNR": fnr,
            "precision": precision
        })

    return pd.DataFrame(rows)

def run_real_baseline(X, y, dataset_name):

    X_train_real, X_test_real, y_train_real, y_test_real = train_test_split(
        X, y,
        test_size=0.5,
        random_state=42,
        stratify=y
    )

    preprocessor, numerical_cols, categorical_cols = build_preprocessor(X_train_real)
    model = build_logistic_model(preprocessor)

    model.fit(X_train_real, y_train_real)
    metrics, y_pred, y_prob = evaluate_model(model, X_test_real, y_test_real)

    print(f"\n=== {dataset_name}: REAL baseline ===")
    print("Accuracy:", round(metrics["accuracy"], 4))
    print("F1:", round(metrics["f1"], 4))
    print("AUC:", round(metrics["auc"], 4) if pd.notnull(metrics["auc"]) else "nan")

    return {
        "model": model,
        "X_train_real": X_train_real,
        "X_test_real": X_test_real,
        "y_train_real": y_train_real,
        "y_test_real": y_test_real,
        "metrics": metrics,
        "numerical_cols": numerical_cols,
        "categorical_cols": categorical_cols
    }


def run_synthetic_tstr(
    synthetic_train_df,
    X_test_real,
    y_test_real,
    target_col="target"
):

    if target_col not in synthetic_train_df.columns:
        raise ValueError(f"Synthetic dataframe must contain target column '{target_col}'.")

    X_train_synth = synthetic_train_df.drop(columns=[target_col])
    y_train_synth = synthetic_train_df[target_col].astype(int)

    preprocessor, _, _ = build_preprocessor(X_train_synth)
    model = build_logistic_model(preprocessor)

    model.fit(X_train_synth, y_train_synth)
    metrics, y_pred, y_prob = evaluate_model(model, X_test_real, y_test_real)

    print("\n=== Synthetic Train / Real Test ===")
    print("Accuracy:", round(metrics["accuracy"], 4))
    print("F1:", round(metrics["f1"], 4))
    print("AUC:", round(metrics["auc"], 4) if pd.notnull(metrics["auc"]) else "nan")

    return {
        "model": model,
        "metrics": metrics
    }

X_diab, y_diab = prepare_diabetes_data("diabetic_data.csv")

diab_results = run_real_baseline(
    X=X_diab,
    y=y_diab,
    dataset_name="UCI Diabetes"
)

X_credit, y_credit = prepare_german_credit_data("german.data")

credit_results = run_real_baseline(
    X=X_credit,
    y=y_credit,
    dataset_name="German Credit"
)

def add_performance_result(rows, dataset_name, model_name, metrics_dict, test_data="Real"):
    rows.append({
        "Dataset": dataset_name,
        "Model": "Logistic Regression",
        "Train Data": model_name,
        "Test Data": test_data,
        "Accuracy": round(metrics_dict["accuracy"], 4),
        "F1": round(metrics_dict["f1"], 4),
        "AUC": round(metrics_dict["auc"], 4) if pd.notnull(metrics_dict["auc"]) else None
    })

def add_fairness_result(rows, dataset_name, train_data_name, fairness_df):
    for _, row in fairness_df.iterrows():
        rows.append({
            "Dataset": dataset_name,
            "Model": "Logistic Regression",
            "Train Data": train_data_name,
            "Group Column": row["group_column"],
            "Group Value": row["group_value"],
            "N": int(row["n"]),
            "Positive Rate": round(row["positive_rate"], 4) if pd.notnull(row["positive_rate"]) else None,
            "FPR": round(row["FPR"], 4) if pd.notnull(row["FPR"]) else None,
            "FNR": round(row["FNR"], 4) if pd.notnull(row["FNR"]) else None,
            "Precision": round(row["precision"], 4) if pd.notnull(row["precision"]) else None
        })

performance_rows = []

add_performance_result(performance_rows, "UCI Diabetes", "Real", diab_results["metrics"])
# add_performance_result(performance_rows, "UCI Diabetes", "Synthpop", diab_tstr["metrics"])

add_performance_result(performance_rows, "German Credit", "Real", credit_results["metrics"])
# add_performance_result(performance_rows, "German Credit", "Synthpop", credit_tstr["metrics"])

performance_table = pd.DataFrame(performance_rows)
print(performance_table)

fairness_diab_real_gender = fairness_by_group(
    diab_results["model"],
    diab_results["X_test_real"],
    diab_results["y_test_real"],
    group_col="gender"
)

fairness_diab_real_race = fairness_by_group(
    diab_results["model"],
    diab_results["X_test_real"],
    diab_results["y_test_real"],
    group_col="race"
)

fairness_credit_real_gender = fairness_by_group(
    credit_results["model"],
    credit_results["X_test_real"],
    credit_results["y_test_real"],
    group_col="gender"
)

fairness_rows = []

add_fairness_result(fairness_rows, "UCI Diabetes", "Real", fairness_diab_real_gender)
add_fairness_result(fairness_rows, "UCI Diabetes", "Real", fairness_diab_real_race)
add_fairness_result(fairness_rows, "German Credit", "Real", fairness_credit_real_gender)
fairness_table = pd.DataFrame(fairness_rows)
fairness_table["Group Value"] = fairness_table["Group Value"].str.lower()
print(fairness_table)